import type { Metadata } from 'next'
import StyledComponentsRegistry from '../lib/style-registry'
// style
import GlobalStyles from '@/styles/global-styles'
// component
import Header from '@/components/header'
import Footer from '@/components/footer'
// context
import { ScrollProvider } from '@/contexts/scroll-context'

/* todo
 *   add fonts
 *   add header, footer here
 *   add global styles
 */

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-tw">
      <body>
        <StyledComponentsRegistry>
          <ScrollProvider>
            <GlobalStyles />
            <Header />
            <main>{children}</main>
            <Footer />
          </ScrollProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
