import { createOptions } from '../utils'

export enum MemberType {
  Constituency = 'constituency',
  NationwideAndOverseas = 'nationwide-and-overseas',
  HighlandAboriginal = 'highland-aboriginal',
  LowlandAboriginal = 'lowland-aboriginal',
}

export const MEMBER_TYPE_LABEL: Readonly<Record<MemberType, string>> = {
  [MemberType.Constituency]: '區域',
  [MemberType.NationwideAndOverseas]: '不分區',
  [MemberType.HighlandAboriginal]: '山地原住民',
  [MemberType.LowlandAboriginal]: '平地原住民',
}

export enum Constituency {
  TaipeiCity1 = 'taipei-city-constituency-1',
  TaipeiCity2 = 'taipei-city-constituency-2',
  TaipeiCity3 = 'taipei-city-constituency-3',
  TaipeiCity4 = 'taipei-city-constituency-4',
  TaipeiCity5 = 'taipei-city-constituency-5',
  TaipeiCity6 = 'taipei-city-constituency-6',
  TaipeiCity7 = 'taipei-city-constituency-7',
  TaipeiCity8 = 'taipei-city-constituency-8',
  NewTaipeiCity1 = 'new-taipei-city-constituency-1',
  NewTaipeiCity2 = 'new-taipei-city-constituency-2',
  NewTaipeiCity3 = 'new-taipei-city-constituency-3',
  NewTaipeiCity4 = 'new-taipei-city-constituency-4',
  NewTaipeiCity5 = 'new-taipei-city-constituency-5',
  NewTaipeiCity6 = 'new-taipei-city-constituency-6',
  NewTaipeiCity7 = 'new-taipei-city-constituency-7',
  NewTaipeiCity8 = 'new-taipei-city-constituency-8',
  NewTaipeiCity9 = 'new-taipei-city-constituency-9',
  NewTaipeiCity10 = 'new-taipei-city-constituency-10',
  NewTaipeiCity11 = 'new-taipei-city-constituency-11',
  NewTaipeiCity12 = 'new-taipei-city-constituency-12',
  TaoyuanCity1 = 'taoyuan-city-constituency-1',
  TaoyuanCity2 = 'taoyuan-city-constituency-2',
  TaoyuanCity3 = 'taoyuan-city-constituency-3',
  TaoyuanCity4 = 'taoyuan-city-constituency-4',
  TaoyuanCity5 = 'taoyuan-city-constituency-5',
  TaoyuanCity6 = 'taoyuan-city-constituency-6',
  TaichungCity1 = 'taichung-city-constituency-1',
  TaichungCity2 = 'taichung-city-constituency-2',
  TaichungCity3 = 'taichung-city-constituency-3',
  TaichungCity4 = 'taichung-city-constituency-4',
  TaichungCity5 = 'taichung-city-constituency-5',
  TaichungCity6 = 'taichung-city-constituency-6',
  TaichungCity7 = 'taichung-city-constituency-7',
  TaichungCity8 = 'taichung-city-constituency-8',
  TainanCity1 = 'tainan-city-constituency-1',
  TainanCity2 = 'tainan-city-constituency-2',
  TainanCity3 = 'tainan-city-constituency-3',
  TainanCity4 = 'tainan-city-constituency-4',
  TainanCity5 = 'tainan-city-constituency-5',
  TainanCity6 = 'tainan-city-constituency-6',
  KaohsiungCity1 = 'kaohsiung-city-constituency-1',
  KaohsiungCity2 = 'kaohsiung-city-constituency-2',
  KaohsiungCity3 = 'kaohsiung-city-constituency-3',
  KaohsiungCity4 = 'kaohsiung-city-constituency-4',
  KaohsiungCity5 = 'kaohsiung-city-constituency-5',
  KaohsiungCity6 = 'kaohsiung-city-constituency-6',
  KaohsiungCity7 = 'kaohsiung-city-constituency-7',
  KaohsiungCity8 = 'kaohsiung-city-constituency-8',
  HsinchuCounty1 = 'hsinchu-county-constituency-1',
  HsinchuCounty2 = 'hsinchu-county-constituency-2',
  MiaoliCounty1 = 'miaoli-county-constituency-1',
  MiaoliCounty2 = 'miaoli-county-constituency-2',
  ChanghuaCounty1 = 'changhua-county-constituency-1',
  ChanghuaCounty2 = 'changhua-county-constituency-2',
  ChanghuaCounty3 = 'changhua-county-constituency-3',
  ChanghuaCounty4 = 'changhua-county-constituency-4',
  NantouCounty1 = 'nantou-county-constituency-1',
  NantouCounty2 = 'nantou-county-constituency-2',
  YunlinCounty1 = 'yunlin-county-constituency-1',
  YunlinCounty2 = 'yunlin-county-constituency-2',
  ChiayiCounty1 = 'chiayi-county-constituency-1',
  ChiayiCounty2 = 'chiayi-county-constituency-2',
  PingtungCounty1 = 'pingtung-county-constituency-1',
  PingtungCounty2 = 'pingtung-county-constituency-2',
  YilanCounty = 'yilan-county-constituency',
  HualienCounty = 'hualien-county-constituency',
  TaitungCounty = 'Taitung-county-constituency',
  PenghuCounty = 'penghu-county-constituency',
  KinmenCounty = 'kinmen-county-constituency',
  LienchiangCounty = 'lienchiang-county-constituency',
  KeelungCounty = 'keelung-county-constituency',
  HsinchuCity = 'hsinchu-county-constituency',
  ChiayiCity = 'chiayi-county-constituency',
}

export const CONSTITUENCY_LABEL: Readonly<Record<Constituency, string>> = {
  [Constituency.TaipeiCity1]: '台北市第01選區',
  [Constituency.TaipeiCity2]: '台北市第02選區',
  [Constituency.TaipeiCity3]: '台北市第03選區',
  [Constituency.TaipeiCity4]: '台北市第04選區',
  [Constituency.TaipeiCity5]: '台北市第05選區',
  [Constituency.TaipeiCity6]: '台北市第06選區',
  [Constituency.TaipeiCity7]: '台北市第07選區',
  [Constituency.TaipeiCity8]: '台北市第08選區',
  [Constituency.NewTaipeiCity1]: '新北市第01選區',
  [Constituency.NewTaipeiCity2]: '新北市第02選區',
  [Constituency.NewTaipeiCity3]: '新北市第03選區',
  [Constituency.NewTaipeiCity4]: '新北市第04選區',
  [Constituency.NewTaipeiCity5]: '新北市第05選區',
  [Constituency.NewTaipeiCity6]: '新北市第06選區',
  [Constituency.NewTaipeiCity7]: '新北市第07選區',
  [Constituency.NewTaipeiCity8]: '新北市第08選區',
  [Constituency.NewTaipeiCity9]: '新北市第09選區',
  [Constituency.NewTaipeiCity10]: '新北市第10選區',
  [Constituency.NewTaipeiCity11]: '新北市第11選區',
  [Constituency.NewTaipeiCity12]: '新北市第12選區',
  [Constituency.TaoyuanCity1]: '桃園市第01選區',
  [Constituency.TaoyuanCity2]: '桃園市第02選區',
  [Constituency.TaoyuanCity3]: '桃園市第03選區',
  [Constituency.TaoyuanCity4]: '桃園市第04選區',
  [Constituency.TaoyuanCity5]: '桃園市第05選區',
  [Constituency.TaoyuanCity6]: '桃園市第06選區',
  [Constituency.TaichungCity1]: '台中市第01選區',
  [Constituency.TaichungCity2]: '台中市第02選區',
  [Constituency.TaichungCity3]: '台中市第03選區',
  [Constituency.TaichungCity4]: '台中市第04選區',
  [Constituency.TaichungCity5]: '台中市第05選區',
  [Constituency.TaichungCity6]: '台中市第06選區',
  [Constituency.TaichungCity7]: '台中市第07選區',
  [Constituency.TaichungCity8]: '台中市第08選區',
  [Constituency.TainanCity1]: '台南市第01選區',
  [Constituency.TainanCity2]: '台南市第02選區',
  [Constituency.TainanCity3]: '台南市第03選區',
  [Constituency.TainanCity4]: '台南市第04選區',
  [Constituency.TainanCity5]: '台南市第05選區',
  [Constituency.TainanCity6]: '台南市第06選區',
  [Constituency.KaohsiungCity1]: '高雄市第01選區',
  [Constituency.KaohsiungCity2]: '高雄市第02選區',
  [Constituency.KaohsiungCity3]: '高雄市第03選區',
  [Constituency.KaohsiungCity4]: '高雄市第04選區',
  [Constituency.KaohsiungCity5]: '高雄市第05選區',
  [Constituency.KaohsiungCity6]: '高雄市第06選區',
  [Constituency.KaohsiungCity7]: '高雄市第07選區',
  [Constituency.KaohsiungCity8]: '高雄市第08選區',
  [Constituency.HsinchuCounty1]: '新竹縣第01選區',
  [Constituency.HsinchuCounty2]: '新竹縣第02選區',
  [Constituency.MiaoliCounty1]: '苗栗縣第01選區',
  [Constituency.MiaoliCounty2]: '苗栗縣第02選區',
  [Constituency.ChanghuaCounty1]: '彰化縣第01選區',
  [Constituency.ChanghuaCounty2]: '彰化縣第02選區',
  [Constituency.ChanghuaCounty3]: '彰化縣第03選區',
  [Constituency.ChanghuaCounty4]: '彰化縣第04選區',
  [Constituency.NantouCounty1]: '南投縣第01選區',
  [Constituency.NantouCounty2]: '南投縣第02選區',
  [Constituency.YunlinCounty1]: '雲林縣第01選區',
  [Constituency.YunlinCounty2]: '雲林縣第02選區',
  [Constituency.ChiayiCounty1]: '嘉義縣第01選區',
  [Constituency.ChiayiCounty2]: '嘉義縣第02選區',
  [Constituency.PingtungCounty1]: '屏東縣第01選區',
  [Constituency.PingtungCounty2]: '屏東縣第02選區',
  [Constituency.YilanCounty]: '宜蘭縣選區',
  [Constituency.HualienCounty]: '花蓮縣選區',
  [Constituency.TaitungCounty]: '台東縣選區',
  [Constituency.PenghuCounty]: '澎湖縣選區',
  [Constituency.KinmenCounty]: '金門縣選區',
  [Constituency.LienchiangCounty]: '連江縣選區',
  [Constituency.KeelungCounty]: '基隆市選區',
  [Constituency.HsinchuCity]: '新竹市選區',
  [Constituency.ChiayiCity]: '嘉義市選區',
}

// Options arrays
export const MEMBER_TYPE_OPTIONS = createOptions(MemberType, MEMBER_TYPE_LABEL)
export const CONSTITUENCY_OPTIONS = createOptions(
  Constituency,
  CONSTITUENCY_LABEL
)

export default {
  MemberType,
  MEMBER_TYPE_LABEL,
  Constituency,
  CONSTITUENCY_LABEL,
  MEMBER_TYPE_OPTIONS,
  CONSTITUENCY_OPTIONS,
}
