export enum MemberType {
  Constituency = 'constituency',
  NationwideAndOverseas = 'nationwide-and-overseas',
  HighlandAboriginal = 'highland-aboriginal',
  LowlandAboriginal = 'lowland-aboriginal',
}

export const MEMBER_TYPE_LABEL: Readonly<Record<MemberType, string>> = {
  [MemberType.Constituency]: '區域',
  [MemberType.NationwideAndOverseas]: '不分區',
  [MemberType.HighlandAboriginal]: '山地原住民',
  [MemberType.LowlandAboriginal]: '平地原住民',
}

export enum Constituency {
  TaipeiCity1 = 'taipei-city-constituency-1',
  TaipeiCity2 = 'taipei-city-constituency-2',
  TaipeiCity3 = 'taipei-city-constituency-3',
  TaipeiCity4 = 'taipei-city-constituency-4',
  TaipeiCity5 = 'taipei-city-constituency-5',
  TaipeiCity6 = 'taipei-city-constituency-6',
  TaipeiCity7 = 'taipei-city-constituency-7',
  TaipeiCity8 = 'taipei-city-constituency-8',
  NewTaipeiCity1 = 'new-taipei-city-constituency-1',
  NewTaipeiCity2 = 'new-taipei-city-constituency-2',
  NewTaipeiCity3 = 'new-taipei-city-constituency-3',
  NewTaipeiCity4 = 'new-taipei-city-constituency-4',
  NewTaipeiCity5 = 'new-taipei-city-constituency-5',
  NewTaipeiCity6 = 'new-taipei-city-constituency-6',
  NewTaipeiCity7 = 'new-taipei-city-constituency-7',
  NewTaipeiCity8 = 'new-taipei-city-constituency-8',
  NewTaipeiCity9 = 'new-taipei-city-constituency-9',
  NewTaipeiCity10 = 'new-taipei-city-constituency-10',
  NewTaipeiCity11 = 'new-taipei-city-constituency-11',
  NewTaipeiCity12 = 'new-taipei-city-constituency-12',
  TaoyuanCity1 = 'taoyuan-city-constituency-1',
  TaoyuanCity2 = 'taoyuan-city-constituency-2',
  TaoyuanCity3 = 'taoyuan-city-constituency-3',
  TaoyuanCity4 = 'taoyuan-city-constituency-4',
  TaoyuanCity5 = 'taoyuan-city-constituency-5',
  TaoyuanCity6 = 'taoyuan-city-constituency-6',
  TaichungCity1 = 'taichung-city-constituency-1',
  TaichungCity2 = 'taichung-city-constituency-2',
  TaichungCity3 = 'taichung-city-constituency-3',
  TaichungCity4 = 'taichung-city-constituency-4',
  TaichungCity5 = 'taichung-city-constituency-5',
  TaichungCity6 = 'taichung-city-constituency-6',
  TaichungCity7 = 'taichung-city-constituency-7',
  TaichungCity8 = 'taichung-city-constituency-8',
  TainanCity1 = 'tainan-city-constituency-1',
  TainanCity2 = 'tainan-city-constituency-2',
  TainanCity3 = 'tainan-city-constituency-3',
  TainanCity4 = 'tainan-city-constituency-4',
  TainanCity5 = 'tainan-city-constituency-5',
  TainanCity6 = 'tainan-city-constituency-6',
  KaohsiungCity1 = 'kaohsiung-city-constituency-1',
  KaohsiungCity2 = 'kaohsiung-city-constituency-2',
  KaohsiungCity3 = 'kaohsiung-city-constituency-3',
  KaohsiungCity4 = 'kaohsiung-city-constituency-4',
  KaohsiungCity5 = 'kaohsiung-city-constituency-5',
  KaohsiungCity6 = 'kaohsiung-city-constituency-6',
  KaohsiungCity7 = 'kaohsiung-city-constituency-7',
  KaohsiungCity8 = 'kaohsiung-city-constituency-8',
  HsinchuCounty1 = 'hsinchu-county-constituency-1',
  HsinchuCounty2 = 'hsinchu-county-constituency-2',
  MiaoliCounty1 = 'miaoli-county-constituency-1',
  MiaoliCounty2 = 'miaoli-county-constituency-2',
  ChanghuaCounty1 = 'changhua-county-constituency-1',
  ChanghuaCounty2 = 'changhua-county-constituency-2',
  ChanghuaCounty3 = 'changhua-county-constituency-3',
  ChanghuaCounty4 = 'changhua-county-constituency-4',
  NantouCounty1 = 'nantou-county-constituency-1',
  NantouCounty2 = 'nantou-county-constituency-2',
  YunlinCounty1 = 'yunlin-county-constituency-1',
  YunlinCounty2 = 'yunlin-county-constituency-2',
  ChiayiCounty1 = 'chiayi-county-constituency-1',
  ChiayiCounty2 = 'chiayi-county-constituency-2',
  PingtungCounty1 = 'pingtung-county-constituency-1',
  PingtungCounty2 = 'pingtung-county-constituency-2',
  YilanCounty = 'yilan-county-constituency',
  HualienCounty = 'hualien-county-constituency',
  TaitungCounty = 'Taitung-county-constituency',
  PenghuCounty = 'penghu-county-constituency',
  KinmenCounty = 'kinmen-county-constituency',
  LienchiangCounty = 'lienchiang-county-constituency',
  KeelungCounty = 'keelung-county-constituency',
  HsinchuCity = 'hsinchu-county-constituency',
  ChiayiCity = 'chiayi-county-constituency',
}

export const CONSTITUENCY_LABEL: Readonly<Record<Constituency, string>> = {
  [Constituency.TaipeiCity1]: '臺北市第一選區',
  [Constituency.TaipeiCity2]: '臺北市第二選區',
  [Constituency.TaipeiCity3]: '臺北市第三選區',
  [Constituency.TaipeiCity4]: '臺北市第四選區',
  [Constituency.TaipeiCity5]: '臺北市第五選區',
  [Constituency.TaipeiCity6]: '臺北市第六選區',
  [Constituency.TaipeiCity7]: '臺北市第七選區',
  [Constituency.TaipeiCity8]: '臺北市第八選區',
  [Constituency.NewTaipeiCity1]: '新北市第一選區',
  [Constituency.NewTaipeiCity2]: '新北市第二選區',
  [Constituency.NewTaipeiCity3]: '新北市第三選區',
  [Constituency.NewTaipeiCity4]: '新北市第四選區',
  [Constituency.NewTaipeiCity5]: '新北市第五選區',
  [Constituency.NewTaipeiCity6]: '新北市第六選區',
  [Constituency.NewTaipeiCity7]: '新北市第七選區',
  [Constituency.NewTaipeiCity8]: '新北市第八選區',
  [Constituency.NewTaipeiCity9]: '新北市第九選區',
  [Constituency.NewTaipeiCity10]: '新北市第十選區',
  [Constituency.NewTaipeiCity11]: '新北市第十一選區',
  [Constituency.NewTaipeiCity12]: '新北市第十二選區',
  [Constituency.TaoyuanCity1]: '桃園市第一選區',
  [Constituency.TaoyuanCity2]: '桃園市第二選區',
  [Constituency.TaoyuanCity3]: '桃園市第三選區',
  [Constituency.TaoyuanCity4]: '桃園市第四選區',
  [Constituency.TaoyuanCity5]: '桃園市第五選區',
  [Constituency.TaoyuanCity6]: '桃園市第六選區',
  [Constituency.TaichungCity1]: '臺中市第一選區',
  [Constituency.TaichungCity2]: '臺中市第二選區',
  [Constituency.TaichungCity3]: '臺中市第三選區',
  [Constituency.TaichungCity4]: '臺中市第四選區',
  [Constituency.TaichungCity5]: '臺中市第五選區',
  [Constituency.TaichungCity6]: '臺中市第六選區',
  [Constituency.TaichungCity7]: '臺中市第七選區',
  [Constituency.TaichungCity8]: '臺中市第八選區',
  [Constituency.TainanCity1]: '臺南市第一選區',
  [Constituency.TainanCity2]: '臺南市第二選區',
  [Constituency.TainanCity3]: '臺南市第三選區',
  [Constituency.TainanCity4]: '臺南市第四選區',
  [Constituency.TainanCity5]: '臺南市第五選區',
  [Constituency.TainanCity6]: '臺南市第六選區',
  [Constituency.KaohsiungCity1]: '高雄市第一選區',
  [Constituency.KaohsiungCity2]: '高雄市第二選區',
  [Constituency.KaohsiungCity3]: '高雄市第三選區',
  [Constituency.KaohsiungCity4]: '高雄市第四選區',
  [Constituency.KaohsiungCity5]: '高雄市第五選區',
  [Constituency.KaohsiungCity6]: '高雄市第六選區',
  [Constituency.KaohsiungCity7]: '高雄市第七選區',
  [Constituency.KaohsiungCity8]: '高雄市第八選區',
  [Constituency.HsinchuCounty1]: '新竹縣第一選區',
  [Constituency.HsinchuCounty2]: '新竹縣第二選區',
  [Constituency.MiaoliCounty1]: '苗栗縣第一選區',
  [Constituency.MiaoliCounty2]: '苗栗縣第二選區',
  [Constituency.ChanghuaCounty1]: '彰化縣第一選區',
  [Constituency.ChanghuaCounty2]: '彰化縣第二選區',
  [Constituency.ChanghuaCounty3]: '彰化縣第三選區',
  [Constituency.ChanghuaCounty4]: '彰化縣第四選區',
  [Constituency.NantouCounty1]: '南投縣第一選區',
  [Constituency.NantouCounty2]: '南投縣第二選區',
  [Constituency.YunlinCounty1]: '雲林縣第一選區',
  [Constituency.YunlinCounty2]: '雲林縣第二選區',
  [Constituency.ChiayiCounty1]: '嘉義縣第一選區',
  [Constituency.ChiayiCounty2]: '嘉義縣第二選區',
  [Constituency.PingtungCounty1]: '屏東縣第一選區',
  [Constituency.PingtungCounty2]: '屏東縣第二選區',
  [Constituency.YilanCounty]: '宜蘭縣選區',
  [Constituency.HualienCounty]: '花蓮縣選區',
  [Constituency.TaitungCounty]: '臺東縣選區',
  [Constituency.PenghuCounty]: '澎湖縣選區',
  [Constituency.KinmenCounty]: '金門縣選區',
  [Constituency.LienchiangCounty]: '連江縣選區',
  [Constituency.KeelungCounty]: '基隆市選區',
  [Constituency.HsinchuCity]: '新竹市選區',
  [Constituency.ChiayiCity]: '嘉義市選區',
}

export enum City {
  Taipei = 'taipei',
  Keelung = 'keelung',
  NewTaipei = 'new-taipei',
  Lienchiang = 'lienchiang',
  Yilan = 'yilan',
  Diauyutai = 'diauyutai',
  HsinchuCity = 'hsinchu-city',
  HsinchuCounty = 'hsinchu-county',
  Taoyuan = 'taoyuan',
  Miaoli = 'miaoli',
  Taichung = 'taichung',
  Changhua = 'changhua',
  Nantou = 'nantou',
  ChiayiCity = 'chiayi-city',
  ChiayiCounty = 'chiayi-county',
  Yunlin = 'yunlin',
  Tainan = 'tainan',
  Kaohsiung = 'kaohsiung',
  Nanhai = 'nanhai',
  Penghu = 'penghu',
  Kinmen = 'kinmen',
  Pingtung = 'pingtung',
  Taitung = 'taitung',
  Hualien = 'hualien',
}

export const CITY_LABEL: Readonly<Record<City, string>> = {
  [City.Taipei]: '臺北市',
  [City.Keelung]: '基隆市',
  [City.NewTaipei]: '新北市',
  [City.Lienchiang]: '連江縣',
  [City.Yilan]: '宜蘭縣',
  [City.Diauyutai]: '釣魚臺',
  [City.HsinchuCity]: '新竹市',
  [City.HsinchuCounty]: '新竹縣',
  [City.Taoyuan]: '桃園市',
  [City.Miaoli]: '苗栗縣',
  [City.Taichung]: '臺中市',
  [City.Changhua]: '彰化縣',
  [City.Nantou]: '南投縣',
  [City.ChiayiCity]: '嘉義市',
  [City.ChiayiCounty]: '嘉義縣',
  [City.Yunlin]: '雲林縣',
  [City.Tainan]: '臺南市',
  [City.Kaohsiung]: '高雄市',
  [City.Nanhai]: '南海島',
  [City.Penghu]: '澎湖縣',
  [City.Kinmen]: '金門縣',
  [City.Pingtung]: '屏東縣',
  [City.Taitung]: '臺東縣',
  [City.Hualien]: '花蓮縣',
}

// Helper types for options
export type Option = {
  label: string
  value: string
}

// Helper function to create options
function createOptions<T extends string>(
  enumObj: Record<string, T>,
  labels: Record<T, string>
): Option[] {
  return Object.entries(enumObj).map(([, value]) => ({
    label: labels[value],
    value,
  }))
}

// Options arrays
export const MEMBER_TYPE_OPTIONS = createOptions(MemberType, MEMBER_TYPE_LABEL)
export const CONSTITUENCY_OPTIONS = createOptions(
  Constituency,
  CONSTITUENCY_LABEL
)
export const CITY_OPTIONS = createOptions(City, CITY_LABEL)
