export const MEMBER_TYPE = Object.freeze({
  constituency: 'constituency',
  nationwideAndOverseas: 'nationwide-and-overseas',
  highlandAboriginal: 'highland-aboriginal',
  lowlandAboriginal: 'lowland-aboriginal',
})

export const MEMBER_TYPE_LABEL = Object.freeze({
  constituency: '區域',
  nationwideAndOverseas: '不分區',
  highlandAboriginal: '山地原住民',
  lowlandAboriginal: '平地原住民',
})

export const MEMBER_TYPE_OPTIONS = Object.freeze(
  Object.keys(MEMBER_TYPE).map((key) => ({
    label: MEMBER_TYPE_LABEL[key as keyof typeof MEMBER_TYPE_LABEL],
    value: MEMBER_TYPE[key as keyof typeof MEMBER_TYPE],
  }))
)

export const CONSTITUENCY = Object.freeze({
  taipeiCityConstituency1: 'taipei-city-constituency-1',
  taipeiCityConstituency2: 'taipei-city-constituency-2',
  taipeiCityConstituency3: 'taipei-city-constituency-3',
  taipeiCityConstituency4: 'taipei-city-constituency-4',
  taipeiCityConstituency5: 'taipei-city-constituency-5',
  taipeiCityConstituency6: 'taipei-city-constituency-6',
  taipeiCityConstituency7: 'taipei-city-constituency-7',
  taipeiCityConstituency8: 'taipei-city-constituency-8',
  newTaipeiCityConstituency1: 'new-taipei-city-constituency-1',
  newTaipeiCityConstituency2: 'new-taipei-city-constituency-2',
  newTaipeiCityConstituency3: 'new-taipei-city-constituency-3',
  newTaipeiCityConstituency4: 'new-taipei-city-constituency-4',
  newTaipeiCityConstituency5: 'new-taipei-city-constituency-5',
  newTaipeiCityConstituency6: 'new-taipei-city-constituency-6',
  newTaipeiCityConstituency7: 'new-taipei-city-constituency-7',
  newTaipeiCityConstituency8: 'new-taipei-city-constituency-8',
  newTaipeiCityConstituency9: 'new-taipei-city-constituency-9',
  newTaipeiCityConstituency10: 'new-taipei-city-constituency-10',
  newTaipeiCityConstituency11: 'new-taipei-city-constituency-11',
  newTaipeiCityConstituency12: 'new-taipei-city-constituency-12',
  taoyuanCityConstituency1: 'taoyuan-city-constituency-1',
  taoyuanCityConstituency2: 'taoyuan-city-constituency-2',
  taoyuanCityConstituency3: 'taoyuan-city-constituency-3',
  taoyuanCityConstituency4: 'taoyuan-city-constituency-4',
  taoyuanCityConstituency5: 'taoyuan-city-constituency-5',
  taoyuanCityConstituency6: 'taoyuan-city-constituency-6',
  taichungCityConstituency1: 'taichung-city-constituency-1',
  taichungCityConstituency2: 'taichung-city-constituency-2',
  taichungCityConstituency3: 'taichung-city-constituency-3',
  taichungCityConstituency4: 'taichung-city-constituency-4',
  taichungCityConstituency5: 'taichung-city-constituency-5',
  taichungCityConstituency6: 'taichung-city-constituency-6',
  taichungCityConstituency7: 'taichung-city-constituency-7',
  taichungCityConstituency8: 'taichung-city-constituency-8',
  tainanCityConstituency1: 'tainan-city-constituency-1',
  tainanCityConstituency2: 'tainan-city-constituency-2',
  tainanCityConstituency3: 'tainan-city-constituency-3',
  tainanCityConstituency4: 'tainan-city-constituency-4',
  tainanCityConstituency5: 'tainan-city-constituency-5',
  tainanCityConstituency6: 'tainan-city-constituency-6',
  kaohsiungCityConstituency1: 'kaohsiung-city-constituency-1',
  kaohsiungCityConstituency2: 'kaohsiung-city-constituency-2',
  kaohsiungCityConstituency3: 'kaohsiung-city-constituency-3',
  kaohsiungCityConstituency4: 'kaohsiung-city-constituency-4',
  kaohsiungCityConstituency5: 'kaohsiung-city-constituency-5',
  kaohsiungCityConstituency6: 'kaohsiung-city-constituency-6',
  kaohsiungCityConstituency7: 'kaohsiung-city-constituency-7',
  kaohsiungCityConstituency8: 'kaohsiung-city-constituency-8',
  hsinchuCountyConstituency1: 'hsinchu-county-constituency-1',
  hsinchuCountyConstituency2: 'hsinchu-county-constituency-2',
  miaoliCountyConstituency1: 'miaoli-county-constituency-1',
  miaoliCountyConstituency2: 'miaoli-county-constituency-2',
  changhuaCountyConstituency1: 'changhua-county-constituency-1',
  changhuaCountyConstituency2: 'changhua-county-constituency-2',
  changhuaCountyConstituency3: 'changhua-county-constituency-3',
  changhuaCountyConstituency4: 'changhua-county-constituency-4',
  nantouCountyConstituency1: 'nantou-county-constituency-1',
  nantouCountyConstituency2: 'nantou-county-constituency-2',
  yunlinCountyConstituency1: 'yunlin-county-constituency-1',
  yunlinCountyConstituency2: 'yunlin-county-constituency-2',
  chiayiCountyConstituency1: 'chiayi-county-constituency-1',
  chiayiCountyConstituency2: 'chiayi-county-constituency-2',
  pingtungCountyConstituency1: 'pingtung-county-constituency-1',
  pingtungCountyConstituency2: 'pingtung-county-constituency-2',
  yilanCountyConstituency: 'yilan-county-constituency',
  hualienCountyConstituency: 'hualien-county-constituency',
  taitungCountyConstituency: 'Taitung-county-constituency',
  penghuCountyConstituency: 'penghu-county-constituency',
  kinmenCountyConstituency: 'kinmen-county-constituency',
  lienchiangCountyConstituency: 'lienchiang-county-constituency',
  keelungCountyConstituency: 'keelung-county-constituency',
  hsinchuCountyConstituency: 'hsinchu-county-constituency',
  chiayiCountyConstituency: 'chiayi-county-constituency',
})

export const CONSTITUENCY_LABEL = Object.freeze({
  taipeiCityConstituency1: '臺北市第一選區',
  taipeiCityConstituency2: '臺北市第二選區',
  taipeiCityConstituency3: '臺北市第三選區',
  taipeiCityConstituency4: '臺北市第四選區',
  taipeiCityConstituency5: '臺北市第五選區',
  taipeiCityConstituency6: '臺北市第六選區',
  taipeiCityConstituency7: '臺北市第七選區',
  taipeiCityConstituency8: '臺北市第八選區',
  newTaipeiCityConstituency1: '新北市第一選區',
  newTaipeiCityConstituency2: '新北市第二選區',
  newTaipeiCityConstituency3: '新北市第三選區',
  newTaipeiCityConstituency4: '新北市第四選區',
  newTaipeiCityConstituency5: '新北市第五選區',
  newTaipeiCityConstituency6: '新北市第六選區',
  newTaipeiCityConstituency7: '新北市第七選區',
  newTaipeiCityConstituency8: '新北市第八選區',
  newTaipeiCityConstituency9: '新北市第九選區',
  newTaipeiCityConstituency10: '新北市第十選區',
  newTaipeiCityConstituency11: '新北市第十一選區',
  newTaipeiCityConstituency12: '新北市第十二選區',
  taoyuanCityConstituency1: '桃園市第一選區',
  taoyuanCityConstituency2: '桃園市第二選區',
  taoyuanCityConstituency3: '桃園市第三選區',
  taoyuanCityConstituency4: '桃園市第四選區',
  taoyuanCityConstituency5: '桃園市第五選區',
  taoyuanCityConstituency6: '桃園市第六選區',
  taichungCityConstituency1: '臺中市第一選區',
  taichungCityConstituency2: '臺中市第二選區',
  taichungCityConstituency3: '臺中市第三選區',
  taichungCityConstituency4: '臺中市第四選區',
  taichungCityConstituency5: '臺中市第五選區',
  taichungCityConstituency6: '臺中市第六選區',
  taichungCityConstituency7: '臺中市第七選區',
  taichungCityConstituency8: '臺中市第八選區',
  tainanCityConstituency1: '臺南市第一選區',
  tainanCityConstituency2: '臺南市第二選區',
  tainanCityConstituency3: '臺南市第三選區',
  tainanCityConstituency4: '臺南市第四選區',
  tainanCityConstituency5: '臺南市第五選區',
  tainanCityConstituency6: '臺南市第六選區',
  kaohsiungCityConstituency1: '高雄市第一選區',
  kaohsiungCityConstituency2: '高雄市第二選區',
  kaohsiungCityConstituency3: '高雄市第三選區',
  kaohsiungCityConstituency4: '高雄市第四選區',
  kaohsiungCityConstituency5: '高雄市第五選區',
  kaohsiungCityConstituency6: '高雄市第六選區',
  kaohsiungCityConstituency7: '高雄市第七選區',
  kaohsiungCityConstituency8: '高雄市第八選區',
  hsinchuCountyConstituency1: '新竹縣第一選區',
  hsinchuCountyConstituency2: '新竹縣第二選區',
  miaoliCountyConstituency1: '苗栗縣第一選區',
  miaoliCountyConstituency2: '苗栗縣第二選區',
  changhuaCountyConstituency1: '彰化縣第一選區',
  changhuaCountyConstituency2: '彰化縣第二選區',
  changhuaCountyConstituency3: '彰化縣第三選區',
  changhuaCountyConstituency4: '彰化縣第四選區',
  nantouCountyConstituency1: '南投縣第一選區',
  nantouCountyConstituency2: '南投縣第二選區',
  yunlinCountyConstituency1: '雲林縣第一選區',
  yunlinCountyConstituency2: '雲林縣第二選區',
  chiayiCountyConstituency1: '嘉義縣第一選區',
  chiayiCountyConstituency2: '嘉義縣第二選區',
  pingtungCountyConstituency1: '屏東縣第一選區',
  pingtungCountyConstituency2: '屏東縣第二選區',
  yilanCountyConstituency: '宜蘭縣選區',
  hualienCountyConstituency: '花蓮縣選區',
  taitungCountyConstituency: '臺東縣選區',
  penghuCountyConstituency: '澎湖縣選區',
  kinmenCountyConstituency: '金門縣選區',
  lienchiangCountyConstituency: '連江縣選區',
  keelungCountyConstituency: '基隆市選區',
  hsinchuCountyConstituency: '新竹市選區',
  chiayiCountyConstituency: '嘉義市選區',
})

export const CONSTITUENCY_OPTIONS = Object.freeze(
  Object.keys(CONSTITUENCY).map((key) => ({
    label: CONSTITUENCY_LABEL[key as keyof typeof CONSTITUENCY_LABEL],
    value: CONSTITUENCY[key as keyof typeof CONSTITUENCY],
  }))
)
